import type { AssetPack } from "@/types/portfolio";

import { codePack } from "./code";
import { originalPack } from "./original";
import { retargetPack } from "./retarget";

export const CODE_IMAGE_DIRS = {
  paper: "/portfolio/code/images",
  blush: "/portfolio/code-blush/images",
} as const;

export type PaletteId = keyof typeof CODE_IMAGE_DIRS;

/** Same artwork, blush colourway. Generated by scripts/recolour-palette.mjs. */
const codeBlushPack = retargetPack(codePack, CODE_IMAGE_DIRS.paper, CODE_IMAGE_DIRS.blush);

export const packs = { code: codePack, original: originalPack } as const;

export type PackId = keyof typeof packs;

/**
 * The palette only reaches the code pack: `/original` is a fixed reference and its
 * artwork is not ours to recolour.
 */
export function getPack(id: PackId, palette: PaletteId = "blush"): AssetPack {
  if (id === "original") return originalPack;
  return palette === "blush" ? codeBlushPack : codePack;
}

/** Maps a pack to its route prefix - the code pack lives at the site root. */
export function packHref(id: PackId, path: string): string {
  const clean = path === "/" ? "" : path;
  return id === "original" ? `/original${clean}` : path;
}

export { codePack, codeBlushPack, originalPack };
